### ISSUE TITLE
Insomnia complains about missing crypto-js

### ISSUE THREAD

**Issue by jozydapozy** [anson-vandoren/insomnia-plugin-binance-signing#1]
`Cannot find module 'crypto-js'.`
How can I install crypto-js?

**Comment by anson-vandoren** [comment]
If you installed it through Insomnia Preferences, Insomnia should've grabbed the correct dependencies. If you installed this plugin manually, or if Insomnia didn't correctly install it for some reason, you can go to the appropriate plugin folder in a terminal window and type `npm install` to pull in the dependencies. If you're not sure where the plugin folder is, go to Application > Preferences > Plugins, then click "Reveal Plugins Folder". On Linux, this would likely be `~/.config/Insomnia/plugins/insomnia-plugin-binance-signing`
